openapi: 3.0.1
info:
  title: JsonPlaceHolder
  description: API Definition of JsonPlaceHolder
  version: 1.0.0
servers:
- url: http://localhost:8290/jsonplaceholder
paths:
  /:
    get:
      responses:
        default:
          description: Default response
  /getOnePost/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /commentsForPost:
    get:
      parameters:
      - name: postId
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
  /createPost:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
