openapi: 3.0.1
info:
  title: POX2JSON
  description: API Definition of POX2JSON
  version: 1.0.0
servers:
- url: http://localhost:8290/pox2json
paths:
  /:
    get:
      responses:
        default:
          description: Default response
