openapi: 3.0.1
info:
  title: world
  description: API Definition of world
  version: 1.0.0
servers:
- url: http://localhost:8290/world
paths:
  /:
    get:
      responses:
        default:
          description: Default response
